include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    always_declare_return_types: error

  exclude:
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart

linter:
  rules:
    - require_trailing_commas
