name: tools
description: A project for inspecting device characteristics.
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  device_info: ^0.4.2+7 
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter 
  pedantic: ^1.9.0

flutter:
  uses-material-design: true