name: device_frame_community
description: Mockups for common devices.
version: 1.0.2
homepage: https://github.com/the-mac/flutter_device_preview/device_frame_community

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  freezed_annotation: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.4
  json_serializable: ^6.0.1
  freezed: ^1.0.0
  flutter_lints: ^1.0.4
  xml: ^5.3.1
  recase: ^4.0.0
